/* Tables */
CREATE TABLE USER (
    Username VARCHAR(64) NOT NULL,
    Display_Name VARCHAR(64) NOT NULL,
    Is_Creator BOOLEAN NOT NULL,
    Password TEXT NOT NULL,
    PRIMARY KEY (Username)
);
CREATE TABLE PODCAST (
    PodcastID INTEGER NOT NULL,
    Description TEXT NOT NULL,
    Title VARCHAR(64) NOT NULL,
    Thumbnail TEXT NOT NULL,
    USER_Username VARCHAR(64) NOT NULL,
    PRIMARY KEY (PodcastID),
    FOREIGN KEY (USER_Username) REFERENCES USER(Username) ON DELETE CASCADE
);
CREATE TABLE EPISODE (
    PODCAST_PodcastID INTEGER NOT NULL,
    EpisodeID INTEGER NOT NULL,
    Title VARCHAR(64) NOT NULL,
    Release_Date REAL NOT NULL,
    Track TEXT NOT NULL,
    Description TEXT NOT NULL,
    PRIMARY KEY (PODCAST_PodcastID, EpisodeID),
    FOREIGN KEY (PODCAST_PodcastID) REFERENCES PODCAST(PodcastID) ON DELETE CASCADE
);
CREATE TABLE COMMENT (
    EPISODE_PODCAST_PodcastID INTEGER NOT NULL,
    EPISODE_EpisodeID INTEGER NOT NULL,
    USER_Username VARCHAR(64) NOT NULL,
    Date_Published REAL NOT NULL,
    Content TEXT NOT NULL,
    PRIMARY KEY (EPISODE_PODCAST_PodcastID, EPISODE_EpisodeID, USER_Username, Date_Published),
    FOREIGN KEY (EPISODE_PODCAST_PodcastID, EPISODE_EpisodeID) REFERENCES EPISODE(PODCAST_PodcastID, EpisodeID) ON DELETE CASCADE,
    FOREIGN KEY (USER_Username) REFERENCES USER(Username) ON DELETE CASCADE
);
CREATE TABLE CATEGORY (
    Name VARCHAR(64) NOT NULL,
    PRIMARY KEY (Name)
);
CREATE TABLE FOLLOWING (
    USER_Username VARCHAR(64) NOT NULL,
    PODCAST_PodcastID INTEGER NOT NULL,
    PRIMARY KEY (USER_Username, PODCAST_PodcastID),
    FOREIGN KEY (USER_Username) REFERENCES USER(Username) ON DELETE CASCADE,
    FOREIGN KEY (PODCAST_PodcastID) REFERENCES PODCAST(PodcastID) ON DELETE CASCADE
);
CREATE TABLE PODCAST_CATEGORY (
    PODCAST_PodcastID INTEGER NOT NULL,
    CATEGORY_Name VARCHAR(64) NOT NULL,
    PRIMARY KEY (PODCAST_PodcastID, CATEGORY_Name),
    FOREIGN KEY (PODCAST_PodcastID) REFERENCES PODCAST(PodcastID) ON DELETE CASCADE,
    FOREIGN KEY (CATEGORY_Name) REFERENCES CATEGORY(Name) ON DELETE CASCADE
);